### ISSUE TITLE
Cant' navigate to image files

### ISSUE THREAD

**Issue by Caleb-Martin** [conversionfoundry/breeze#109]
When linking a image to an custom type via the front end, you can not navigaite through the file structure to choose 1 particular file. you can only see the top folder items in the assets, and no further.

**Comment by Caleb-Martin** [comment]
could you give me a ETA when you will start this one? Cheers

**Comment by isaacfreeman** [comment]
Just finishing this one in my own repository, and it should be merged into the main breeze code soon.
