### ISSUE TITLE
Assets lets you give invalid folder names

### ISSUE THREAD

**Issue by sam-law** [conversionfoundry/breeze#117]
When creating a folder, the system will let you give folder names that aren't valid and don't work e.g. "sam's folder $"

Once you've created a folder with an invalid file name, you can select it and upload files to it, but it never displays the folder contents.

**Comment by albandiguer** [comment]
Hi Sam, thanks

the new version will take care of this
https://github.com/albandiguer/breeze/blob/add_built_in_galleries/app/models/breeze/content/assets/folder.rb#L10
