### ISSUE TITLE
Time to drop the ban on IE for admin pages?

### ISSUE THREAD

**Issue by isaacfreeman** [conversionfoundry/breeze#129]
Currently Breeze blocks people trying to access admin pages using Internet Explorer. This made some sense when IE6 was current, but it's probably not necessary anymore.

The relevant code is in breeze/admin/admin_controller.rb, with a view at breeze/errors/ie.html.erb

**Comment by sam-law** [comment]
I see no reason to not allow IE9 and up access to the back end, since it's relatively standards compliant

**Comment by isaacfreeman** [comment]
Moved to Basecamp for discussion as a feature
