### ISSUE TITLE
Ability to sort blog posts

### ISSUE THREAD

**Issue by LauraLC** [conversionfoundry/breeze#160]
It would be great to be able to sort blog posts by clicking on their headers in Breeze Admin (e.g. Post Title for alphabetical, authors, tags, comment counts and date) - would make it easier when there's many posts to sort through if looking for one in particular. Furthermore, an ability to 'search posts' would be great also. Cheers!

**Comment by isaacfreeman** [comment]
We need to restore this kind of filtering in a standardised way throughout Breeze. Anywhere where there's a table.

**Comment by isaacfreeman** [comment]
Moved this to Basecamp, as it's a feature request rather than an issue.
