### ISSUE TITLE
Login form excessive padding.

### ISSUE THREAD

**Issue by sam-law** [conversionfoundry/breeze#186]
The current version of the sign in form has excessive padding at the bottom.
![2013-02-22_1640](https://f.cloud.github.com/assets/684902/183536/c7ecb9f8-7ca1-11e2-9794-7670458b3455.png)

The following css changes:
`body.breeze-login #login` padding to `15px 0 38px 0`
`body.breeze-login #login #forgot` margin to `-44px 16px -20px`

Would make it look tidier
![2013-02-22_1646](https://f.cloud.github.com/assets/684902/183553/76d80e68-7ca2-11e2-8d21-74d70f51df85.png)

**Comment by isaacfreeman** [comment]
Fixed
