### ISSUE TITLE
Image browse icon on editor pane is not correct size

### ISSUE THREAD

**Issue by sam-law** [conversionfoundry/breeze#194]
When using the editor pane, alongside an image field there's a button you can click to bring up a list of all the assets.

The width/height of this element is incorrect so you end up seeing a cropped version of the image.
![2013-03-14_1251](https://f.cloud.github.com/assets/684902/256854/f5e93aa6-8c38-11e2-99e0-d11babc43270.png)

Modifying `.image_field .browse` `width: 24px;` `height: 24xpx;` would correct this.
![2013-03-14_1250](https://f.cloud.github.com/assets/684902/256853/ec359a9a-8c38-11e2-8635-e8fd9f9a5ebe.png)

**Comment by isaacfreeman** [comment]
We fixed this at some point.
