### ISSUE TITLE
After initial creation of a custom type, fields cannot be updated

### ISSUE THREAD

**Issue by ShaneNZ** [conversionfoundry/breeze#22]
Observed on Leftclick site (Breeze version?)

Steps
1. Create a CT, one or more fields
2. Save the CT.
3. Go back and edit the CT:
3a. Adding a field and saving the CT seems to work, but the field isn't available in the partial - partial generates an error.
3b. Editing a field name used seems to work, but doesn't update for the partial - previous name still exists for the partial, new name doesn't exist at all.
4. Editing the field label (used on the front end) works _sometimes_ - erratic, and unable to recreate reliably.

**Comment by isaacfreeman** [comment]
It looks like this was fixed by Alban during his work on custom types. Marking as closed.
