### ISSUE TITLE
Closing a custom type tab in the backend throws away all changes without warning

### ISSUE THREAD

**Issue by ShaneNZ** [conversionfoundry/breeze#23]
Observed on Leftclick site (Breeze version?)

Closing a CT tab in the backend, either with the x in the tab or via 'Cancel' on the right throws away all changes without confirmation.

NB: this could be true of all tabs/content editing situations?

**Comment by sam-law** [comment]
Related issue is "deleting" content requires confirmation on only some things. So if you delete a piece of content on the front-end it asks for confirmation. Deleting a partial requires no confirmation whatsoever (it just does it).
