### ISSUE TITLE
Editing a custom type after content has been created onsite causes issues

### ISSUE THREAD

**Issue by ShaneNZ** [conversionfoundry/breeze#25]
Observed on Leftclick site (Breeze version?)

Steps:
1. Create a CT (with or without a partial)
2. Insert the custom type into a page
3. Go to the backend and update the name of the custom type
    \* CT cannot be edited on the front end - gives an endless spinner
    \* Deleting the CT works most of the time, but at other times it does not - unable to recreate this reliably

**Comment by isaacfreeman** [comment]
Resolved during Alban's custom types update.
