### ISSUE TITLE
Custom types cannot be deleted and recreated - name collision

### ISSUE THREAD

**Issue by ShaneNZ** [conversionfoundry/breeze#27]
Observed on Leftclick site (Breeze version?)

Steps:
1. Create a custom type called "foo", create a couple of fields within it, save it.
2. Delete "foo".
3. Create a new CT called "foo", with different fields in it.
   - Breeze uses the old instance of the CT with the partial and on the front end

NB: reloading the page on the front end updated the fields presented in the content editor, but the partial still expected/required the old fields.

**Comment by sam-law** [comment]
Once a partial is created, if you modify it, all versions of that partial across the site need to be deleted/re-added.

**Comment by ShaneNZ** [comment]
When you're talking about "modifying", do you mean partial or custom type?

_Shane Goodwin | User Experience Designer | *_LeftClick*
31 Elizabeth Street, Christchurch, New Zealand
_Tel:_ _+64 3 379 8984_\* |\* _Web:_ www.leftclick.com

**Comment by isaacfreeman** [comment]
This is working as intended. Changing a custom type doesn't modify the corresponding partial (if any) because the partial may be highly customised by the designer.

Following Alban's work on custom types, we now have better error messages when a partial doesn't work.
