### ISSUE TITLE
Parsing of custom type names with _ and numbers is broken

### ISSUE THREAD

**Issue by ShaneNZ** [conversionfoundry/breeze#28]
Observed on Leftclick site (Breeze version?)

If a CT is created with underscores followed by digits in the name, then Breeze incorrectly strips the underscores out with it generates the default partial name.

Examples:
Create a CT called customtype_one -> Breeze looks for a partial called _customtype_one (correct)
Create a CT called customtype_1 -> Breeze looks for partial called _customtype1 (incorrect)

**Comment by albandiguer** [comment]
Comment on this Shane, basically the behavior for the moment is to get the dynamic class name to retrieve what is the partial name. Changing this is more tricky that is seems to be. However from our conversations I added validation and test concerning the pattern of the name. Avoiding creating classes named 

SuperCustomType(20%)!

We can now enter only letters, digits space, dash and underscores. 

Thanks,
Al
