### ISSUE TITLE
Cannot delete users

### ISSUE THREAD

**Issue by ShaneNZ** [conversionfoundry/breeze#32]
Tried to delete a user from the system, button did nothing. Tried on the LeftClick site.

**Comment by isaacfreeman** [comment]
I fixed a problem like that quite a few months ago. Can't be certain it's the same issue, but I suspect this one is already fixed in current Breeze.

**Comment by albandiguer** [comment]
Hi Shane thanks,
Indeed that works on breeze 1.x. We are about to migrate the company website on this version so I close this.
