### ISSUE TITLE
Cannot add or edit content to region

### ISSUE THREAD

**Issue by sam-law** [conversionfoundry/breeze#51]
Trying to add a piece of content to a region, either a Snippet or a custom type, results in an error.

Looking in the Network tab of Developer Tools.
Content.js errors with - Mongoid::Errors::InvalidFind in Breeze::Admin::ContentsController#create
add.js errors with - NoMethodError in Breeze::Admin::ContentsController#add

Trying to edit a piece of content, as soon as you press ok, the edit snippet window disappears, but the content on-page doesn't change, and reloading the page shows no change was made.
# Seen on

fudgecottage.leftclick.co.nz:3000
# Breeze Components

Breeze: 1.0.0
Breeze Account: 1.0.0
Breeze Apply Online: 1.0.0
Breeze Commerce: 1.1.0
Breeze Pay Online: 0.1.0

**Comment by albandiguer** [comment]
Hi Sam, thanks for the report, this has been solved a month ago or so when the javascript has been cleaned.
