### ISSUE TITLE
Custom Type - Field type Image Field not saving width/height

### ISSUE THREAD

**Issue by sam-law** [conversionfoundry/breeze#52]
When creating or editing a custom type with an image field, specifying width and height is not saved upon pressing save. It appears to be sent in the form submission, but on going in to edit the custom type it's not seen in the width/height fields, and on the front end it's not noted when specifying an image.
# Seen on

fudgecottage.leftclick.co.nz:3000
# Breeze Components

Breeze: 1.0.0
Breeze Account: 1.0.0
Breeze Apply Online: 1.0.0
Breeze Commerce: 1.1.0
Breeze Pay Online: 0.1.0

**Comment by sam-law** [comment]
This is a duplicate of this issue - https://github.com/leftclick/breeze/issues/12
and related to this issue - https://github.com/leftclick/breeze/issues/11

**Comment by isaacfreeman** [comment]
Resolved.
