### ISSUE TITLE
"/home" is inserted into permalinks

### ISSUE THREAD

**Issue by isaacfreeman** [conversionfoundry/breeze#66]
Page permalinks should be

```
fudgecottage.leftclick.co.nz/buy_fudge
```

Currently is

```
fudgecottage.leftclick.co.nz /home /buy_fudge
```

This looks like an issue with the PermalinkGenerator class in mixins/permalinks.rb

**Comment by albandiguer** [comment]
I believe this comes from corrupted data. Spec are passing and the root's slug is not took in consideration when building the permalink except if not unique.

I just refact this part and added some spec for more clarity. 

My advice is to 
- open a console 
- load page of first level
- update the permalink to the expected one
- save
  
  it will save everything in cascade.
