### ISSUE TITLE
Live editing does not update edited component [p1]

### ISSUE THREAD

**Issue by kenbeatson** [conversionfoundry/breeze#73]
Clicking save does nothing - often the changes are saves in the background and after reloading a few times the changes appear.

**Comment by albandiguer** [comment]
Few explanation on this for the record:

Rails 3 comes with logic around caching, and this is also the case for ajax request answers. In this ticket, what is in cause is actually the persistence, as Ken says it is saved apparently but the content displayed is not good. Hence I rename the title of this ticket.
