### ISSUE TITLE
Unify javascripts

### ISSUE THREAD

**Issue by albandiguer** [conversionfoundry/breeze#84]
Avoid having two different set of javascript requirements for admin part or not.

**Comment by isaacfreeman** [comment]
I've given this the Emergency tag, as it's affecting work on a couple of client projects now. It's related to issue #83.

It'd be good to have a standard policy for all Breeze modules, and which we can recommend also be adopted in themes. As a starting point, how about this:
1. a single manifest file for each module, with the module's name ( e.g. breeze.js, breeze_commerce.js ) and linking to all JS files used both front-end and admin
2. a single manifest file for each theme, with the theme's name (this might be overkill in some cases, but it would help theme creators learn how the manifests work)
3. modules typically have two JS files referenced in the manifest: modulename_front.js and modulename_admin.js

It would also be good if we could support CDN delivery through the pipeline.

**Comment by albandiguer** [comment]
see commits around a557548be7f8a40d096af647d9b2b6ee2c80c4f8
